import 'bootstrap/dist/css/bootstrap.css';
import { Inter } from 'next/font/google'
import './globals.css'
import BootstrapClient from '../components/BootstrapClient';
import NavBar from '../components/Navbar';
import { NextAuthProvider } from './Providers';


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Group Blog',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextAuthProvider>
          <NavBar />
          {children}
          <BootstrapClient />
        </NextAuthProvider>
      </body>
    </html>
  )
}
